### ISSUE TITLE
esy bootstrap error on OSX

### ISSUE THREAD

**Issue by nielmond** [onivim/oni2#1856]
OSX 10.14.6

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @esy-ocaml/libffi@github:onivim/libffi#590b041
    # esy-build-package: pwd: /Users/nielmond/.esy/3/b/esy_ocaml__s__libffi-4e776efc
    # esy-build-package: running: 'find' './' '-exec' 'touch' '-t' '200905010101' '{}' '+'
    # esy-build-package: running: 'bash' '-c' 'CFLAGS=-fPIC ./configure --enable-shared=no --enable-static=yes --prefix /Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc'
    checking build system type... x86_64-apple-darwin18.7.0
    checking host system type... x86_64-apple-darwin18.7.0
    checking target system type... x86_64-apple-darwin18.7.0
    continue configure in default builddir "./x86_64-apple-darwin18.7.0"
    ....exec /bin/sh .././configure "--srcdir=.." "--enable-builddir=x86_64-apple-darwin18.7.0" "darwin18.7.0"
    checking build system type... x86_64-apple-darwin18.7.0
    checking host system type... x86_64-apple-darwin18.7.0
    checking target system type... x86_64-apple-darwin18.7.0
    checking for gsed... sed
    checking for a BSD-compatible install... /usr/local/bin/ginstall -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... no
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... gcc3
    checking dependency style of gcc... gcc3
    checking whether gcc and cc understand -c and -o together... yes
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 196608
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert x86_64-apple-darwin18.7.0 file names to x86_64-apple-darwin18.7.0 format... func_convert_file_noop
    checking how to convert x86_64-apple-darwin18.7.0 file names to toolchain format... func_convert_file_noop
    checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... no
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking for dsymutil... dsymutil
    checking for nmedit... nmedit
    checking for lipo... lipo
    checking for otool... otool
    checking for otool64... no
    checking for -single_module linker flag... yes
    checking for -exported_symbols_list linker flag... yes
    checking for -force_load linker flag... yes
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... no
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... no
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... no
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... yes
    checking for gcc option to produce PIC... -fno-common -DPIC
    checking if gcc PIC flag -fno-common -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin18.7.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... no
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... g++ -E
    checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking for g++ option to produce PIC... -fno-common -DPIC
    checking if g++ PIC flag -fno-common -DPIC works... yes
    checking if g++ static flag -static works... no
    checking if g++ supports -c -o file.o... yes
    checking if g++ supports -c -o file.o... (cached) yes
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin18.7.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking size of size_t... 0
    checking for C compiler vendor... clang
    checking CFLAGS for maximum warnings... -Wall
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking sys/mman.h usability... yes
    checking sys/mman.h presence... yes
    checking for sys/mman.h... yes
    checking for mmap... yes
    checking for mkostemp... yes
    checking for sys/mman.h... (cached) yes
    checking for mmap... (cached) yes
    checking whether read-only mmap of a plain file works... yes
    checking whether mmap from /dev/zero works... no
    checking for MAP_ANON(YMOUS)... yes
    checking whether mmap with MAP_ANON(YMOUS) works... yes
    checking for ANSI C header files... (cached) no
    checking for memcpy... yes
    checking for size_t... yes
    checking for working alloca.h... yes
    checking for alloca... yes
    checking size of double... 0
    checking size of long double... 0
    checking whether byte ordering is bigendian... no
    checking assembler .cfi pseudo-op support... yes
    checking for _ prefix in compiled symbols... yes
    checking whether .eh_frame section should be read-only... no
    checking for __attribute__((visibility("hidden")))... no
    clang: error: unsupported option '-print-multi-os-directory'
    clang: error: no input files
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating include/Makefile
    config.status: creating include/ffi.h
    config.status: creating Makefile
    config.status: creating testsuite/Makefile
    config.status: creating man/Makefile
    config.status: creating libffi.pc
    config.status: creating fficonfig.h
    config.status: linking ../src/x86/ffitarget.h to include/ffitarget.h
    config.status: executing buildir commands
    config.status: create top_srcdir/Makefile guessed from local Makefile
    config.status: buggy sed found - it deletes tab in "a" text parts
    config.status: build in x86_64-apple-darwin18.7.0 (HOST=)
    config.status: executing depfiles commands
    config.status: executing libtool commands
    config.status: executing include commands
    config.status: executing src commands
    # esy-build-package: running: 'make'
    MAKE x86_64-apple-darwin18.7.0 :        0 * all-all
    /Applications/Xcode.app/Contents/Developer/usr/bin/make 'AR_FLAGS=' 'CC_FOR_BUILD=' 'CFLAGS=-fPIC  -Wall -fexceptions' 'CXXFLAGS=-g -O2' 'CFLAGS_FOR_BUILD=' 'CFLAGS_FOR_TARGET=' 'INSTALL=/usr/local/bin/ginstall -c' 'INSTALL_DATA=/usr/local/bin/ginstall -c -m 644' 'INSTALL_PROGRAM=/usr/local/bin/ginstall -c' 'INSTALL_SCRIPT=/usr/local/bin/ginstall -c' 'JC1FLAGS=' 'LDFLAGS=' 'LIBCFLAGS=' 'LIBCFLAGS_FOR_TARGET=' 'MAKE=/Applications/Xcode.app/Contents/Developer/usr/bin/make' 'MAKEINFO=/bin/sh /Users/nielmond/.esy/3/b/esy_ocaml__s__libffi-4e776efc/missing makeinfo ' 'PICFLAG=' 'PICFLAG_FOR_TARGET=' 'RUNTESTFLAGS=' 'SHELL=/bin/sh' 'exec_prefix=/Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc' 'infodir=/Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc/share/info' 'libdir=/Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc/lib' 'mandir=/Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc/share/man' 'prefix=/Users/nielmond/.esy/3________________________________________________________________/s/esy_ocaml__s__libffi-4e776efc' 'AR=ar' 'AS=as' 'CC=gcc' 'CXX=g++' 'LD=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld' 'NM=/usr/bin/nm -B' 'RANLIB=ranlib' 'DESTDIR=' all-recursive
    Making all in include
    make[3]: Nothing to be done for `all'.
    Making all in testsuite
    make[3]: Nothing to be done for `all'.
    Making all in man
    make[3]: Nothing to be done for `all'.
    depbase=`echo src/prep_cif.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I. -I../include -Iinclude -I../src   -fPIC  -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF $depbase.Tpo -c -o src/prep_cif.lo ../src/prep_cif.c &&\
    	mv -f $depbase.Tpo $depbase.Plo
    libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -fPIC -Wall -fexceptions -MT src/prep_cif.lo -MD -MP -MF src/.deps/prep_cif.Tpo -c ../src/prep_cif.c -o src/prep_cif.o
    In file included from ../src/prep_cif.c:28:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/stdlib.h:66:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:110:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:196:2: error: unknown type name 'uint8_t'
            uint8_t  ri_uuid[16];
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:197:2: error: unknown type name 'uint64_t'
            uint64_t ri_user_time;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:198:2: error: unknown type name 'uint64_t'
            uint64_t ri_system_time;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:199:2: error: unknown type name 'uint64_t'
            uint64_t ri_pkg_idle_wkups;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:200:2: error: unknown type name 'uint64_t'
            uint64_t ri_interrupt_wkups;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:201:2: error: unknown type name 'uint64_t'
            uint64_t ri_pageins;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:202:2: error: unknown type name 'uint64_t'
            uint64_t ri_wired_size;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:203:2: error: unknown type name 'uint64_t'
            uint64_t ri_resident_size;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:204:2: error: unknown type name 'uint64_t'
            uint64_t ri_phys_footprint;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:205:2: error: unknown type name 'uint64_t'
            uint64_t ri_proc_start_abstime;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:206:2: error: unknown type name 'uint64_t'
            uint64_t ri_proc_exit_abstime;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:210:2: error: unknown type name 'uint8_t'
            uint8_t  ri_uuid[16];
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:211:2: error: unknown type name 'uint64_t'
            uint64_t ri_user_time;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:212:2: error: unknown type name 'uint64_t'
            uint64_t ri_system_time;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:213:2: error: unknown type name 'uint64_t'
            uint64_t ri_pkg_idle_wkups;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:214:2: error: unknown type name 'uint64_t'
            uint64_t ri_interrupt_wkups;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:215:2: error: unknown type name 'uint64_t'
            uint64_t ri_pageins;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:216:2: error: unknown type name 'uint64_t'
            uint64_t ri_wired_size;
            ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/resource.h:217:2: error: unknown type name 'uint64_t'
            uint64_t ri_resident_size;
            ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make[3]: *** [src/prep_cif.lo] Error 1
    make[2]: *** [all-recursive] Error 1
    make[1]: *** [all] Error 2
    make: *** [all-all] Error 2
    error: command failed: 'make' (exited with 2)
    esy-build-package: exiting with errors above...

  building @esy-ocaml/libffi@github:onivim/libffi#590b041
```

**Comment by nielmond** [comment]
I got past this by renaming `/usr/local/include`, as suggested here https://github.com/libffi/libffi/issues/128

I got this same error when trying to run `node install-node-deps.js` (tried that, even though it came later in the instructions.

**Comment by nielmond** [comment]
Now `esy bootstrap` fails with a different error
```
info building esy-skia@github:revery-ui/esy-skia#d60e5fe@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: esy-skia@github:revery-ui/esy-skia#d60e5fe
    # esy-build-package: pwd: /Users/nielmond/.esy/3/b/esy_skia-106e9465
    # esy-build-package: running: 'bash' './esy/build.sh' 'darwin' '/Users/nielmond/.esy/3________________________________________________________________/i/esy_libjpeg_turbo-dc3b4679'
    buildtools                           @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
    common                               @ 9737551d7a52c3db3262db5856e6bcd62c462b92
    third_party/externals/angle2         @ b001528ffa00e7c15a5002124f707570e59a5697
    third_party/externals/dng_sdk        @ 96443b262250c390b0caefbf3eed8463ba35ecae
    third_party/externals/expat          @ android-6.0.1_r55
    third_party/externals/freetype       @ fa6da7bf6dcbcfa22d2464259ad1cccee3233189
    third_party/externals/googletest     @ dd43b9998e9a44a579a7aba6c1309407d1a5ed95
    third_party/externals/harfbuzz       @ 1.4.2
    third_party/externals/icu            @ ec9c1133693148470ffe2e5e53576998e3650c1d
    third_party/externals/imgui          @ 6384eee34f08cb7eab8d835043e1738e4adcdf75
    third_party/externals/jsoncpp        @ 1.0.0
    third_party/externals/libjpeg-turbo  @ 1.5.3
    third_party/externals/libpng         @ v1.6.33
    third_party/externals/libwebp        @ v0.6.1
    third_party/externals/lua            @ v5-3-4
    third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
    third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
    third_party/externals/rapidjson      @ af223d44f4e8d3772cb1ac0ce8bc2a132b51717f
    third_party/externals/sdl            @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
    third_party/externals/sfntly         @ b18b09b6114b9b7fe6fc2f96d8b15e8a72f66916
    third_party/externals/spirv-headers  @ 661ad91124e6af2272afd00f804d8aa276e17107
    third_party/externals/spirv-tools    @ e9e4393b1c5aad7553c05782acefbe32b42644bd
    third_party/externals/swiftshader    @ cbb80f5f0078a9941f3ec43e83e52c3d15a43bea
    third_party/externals/zlib           @ e7afdfe128e01ca480a28f757b571957befdd962
    Traceback (most recent call last):
      File "tools/git-sync-deps", line 254, in <module>
        exit(main(sys.argv[1:]))
      File "tools/git-sync-deps", line 249, in main
        os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 185, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    llvm toolset-7.0 does not need to be manually activated
    ./esy/build.sh: line 44: bin/gn: No such file or directory
    error: command failed: 'bash' './esy/build.sh' 'darwin' '/Users/nielmond/.esy/3________________________________________________________________/i/esy_libjpeg_turbo-dc3b4679' (exited with 255)
    esy-build-package: exiting with errors above...

  building esy-skia@github:revery-ui/esy-skia#d60e5fe
esy: exiting due to errors above
```

**Comment by nielmond** [comment]
The above error looks very much like https://github.com/revery-ui/revery/issues/686. `python --version` is 2.7.18. I also have `python2 --version` resulting in the same version. I do think I have python 3 installed somewhere on my machine.

**Comment by nielmond** [comment]
When I run  `esy run -f --checkhealth` I get the same error but with a little more info included:

```
    error: RPC failed; result=56, HTTP code = 200
    fatal: The remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
```

**Comment by nielmond** [comment]
Eh, that might have been a glitch. Running it a second time just resulted in the same error as before.

**Comment by nielmond** [comment]
Coming back to this. I realized the instance of Python that was being used in the stacktraces is not the same Python I have on my path. It seems to be installed from brew, but trying to upgrade it didn't work. I moved the location of that Python installation, and then it worked!

How does one specify which instance of python to use?

When oni runs the fonts are messed up, but that's a separate issue. I'm unstuck here, but it does seem like there is room to improve the installation process so I guess I'll leave this open.

**Comment by bryphe** [comment]
> Anyway, I moved the location of that Python installation so esy wouldn't find it, and then it worked!

> One question is: How does one specify which instance of python to use?

Glad you got it working, @nielmond !

The actual source of the failure is the [`esy-skia`](https://github.com/revery-ui/esy-skia/) project - that's where python2 is required, and does the detection: https://github.com/revery-ui/esy-skia/blob/c8bded8894f6624a0c1b0b1b2736630754bef62b/esy/build.sh#L6

> I'm unstuck here, but it does seem like there is room to improve the installation process so I guess I'll leave this open.

Since the root cause is with [`esy-skia`](https://github.com/revery-ui/esy-skia) - we should probably move the issue there. I don't think there's any action here in Onivim 2 for this particular issue (although there is certainly room for improvement in the chain of dependencies!)

> When oni runs the fonts are messed up, but that's a separate issue. 

Hmm, are the fonts not showing at all? Or corrupted? Wondering if it's an issue if we have tracked already or not. You'll need to run `esy bootstrap` and `node install-node-deps.js` to get all the dependencies set up.

**Comment by nielmond** [comment]
There were fonts, they just looked bad, like fonts were being replaced inappropriately, and overall looked much worse than the paid version. I went back just now and pulled from master and went through the steps again and it looks OK now. I had run `esy bootstrap` and and `node install-node-deps.js` before, things weren't working so I tried a bunch of things in the process and may have reverted something? So either going through the steps again fixed it or you guys fixed a bug, but either way seems resolved!

**Comment by bryphe** [comment]
> So either going through the steps again fixed it or you guys fixed a bug, but either way seems resolved!

Great news! Thanks @nielmond for the update.  It's possible - been a bunch of work on fonts lately (ie, we bundled and defaulted to JetBrains Mono now). In any case, glad it's working for you now 😄
