### ISSUE TITLE
A notification keeps popping up

### ISSUE THREAD

**Issue by kavitormorsch** [onivim/oni2#2282]
Everytime I press on the coding tab a notification appears saying: "A request has failed. See the output for more information.".
![image](https://user-images.githubusercontent.com/67760452/89932232-af1a0a80-dbe3-11ea-825a-5f1230b25213.png)

**Comment by bryphe** [comment]
Thanks for logging the issue, @kavitormorsch - looks like a bug with our extension integration.

- Do you have any language extensions installed? 
- And which platform are you on - Mac / Windows / Linux?

I need to hook up the `Output` provider as well - so these errors are easier to troubleshoot.

**Comment by lhallam** [comment]
This happens on Windows with the rust-analyzer plugin on any rust file after the binary has been downloaded. A new notification opens for every key press, and there's no completion etc. Running `Go-to definition` also doesn't work but doesn't trigger the notification.

The plugin works fine on Linux, haven't tested Mac.

**Comment by Szune** [comment]
Not sure if this is of use @bryphe, but here are my error logs, setup and steps:

Setup:
* Windows 10,
* matklad.rust-analyzer extension installed from within Onivim 2
* rust-analyzer binaries downloaded and placed inside one of my PATH folders

Steps:
1. Open Onivim 2 in a rust project folder
1. Open a .rs file in the editor

Log:
```
[ERROR]  +530ms Oni2.Service.FileWatcher : 'oni://Welcome': no such file or directory
[ERROR]  +365ms Oni2.Extension.ClientStore : {"$isError":true,"name":"Error","message":"Assertion failed (active editor 'onivim.editor:0' does not exist)","stack":"Error: Assertion failed (active editor 'onivim.editor:0' does not exist)\n    at Object.ok (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\assert.js:14:19)\n    at ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\api\\common\\extHostDocumentsAndEditors.js:79:28)\n    at RPCProtocol._doInvokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:336:31)\n    at RPCProtocol._invokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:321:49)\n    at RPCProtocol._receiveRequest (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:248:36)\n    at RPCProtocol._receiveOneMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:176:30)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:66:56\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:362:35)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\node\\extensionHostProcessSetup.js:145:41\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:362:35)\n    at PersistentProtocol._receiveMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:581:37)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:455:83\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at ProtocolReader.acceptChunk (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:188:37)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:157:61\n    at Socket.listener (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\node\\ipc.net.js:17:40)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)"}
[ERROR]    +2ms Oni2.Extension.ClientStore : {"$isError":true,"name":"Error","message":"Assertion failed (document 'file:///oni%3A//Welcome' does not exist)","stack":"Error: Assertion failed (document 'file:///oni%3A//Welcome' does not exist)\n    at Object.ok (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\assert.js:14:19)\n    at ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\api\\common\\extHostDocumentsAndEditors.js:71:32)\n    at RPCProtocol._doInvokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:336:31)\n    at RPCProtocol._invokeHandler (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:321:49)\n    at RPCProtocol._receiveRequest (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:248:36)\n    at RPCProtocol._receiveOneMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:176:30)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:66:56\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:362:35)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\workbench\\services\\extensions\\node\\extensionHostProcessSetup.js:145:41\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at BufferedEmitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:362:35)\n    at PersistentProtocol._receiveMessage (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:581:37)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:455:83\n    at Emitter.fire (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\common\\event.js:457:42)\n    at ProtocolReader.acceptChunk (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:188:37)\n    at C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\common\\ipc.net.js:157:61\n    at Socket.listener (C:\\Program Files\\Onivim2\\node\\node_modules\\@onivim\\vscode-exthost\\out\\vs\\base\\parts\\ipc\\node\\ipc.net.js:17:40)\n    at Socket.emit (events.js:315:20)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)"}
[ERROR]  +366ms Oni2.Extension.ClientStore : Unhandled workspace message - $checkExists: [[{"$mid":1,"external":"file:///<folder with two separate rust projects, fails to find cargo.toml (still get all the other errors even if opening a specific project)>
[ERROR] +4663ms Oni2.Extension.ClientStore : I tried the following decoders but they all failed:
  "string" decoder: Expected a string, but got null 
  "int" decoder: Expected an int, but got null 
  "float" decoder: Expected a float, but got null  
[ERROR]    +1ms Oni2.Extension.ClientStore : Unhandled method: $registerNavigateTypeSupport - Args: [7]
[ERROR]    +0ms Oni2.Extension.ClientStore : Unhandled method: $registerQuickFixSupport - Args: [8,[{"$serialized":true,"language":"rust","scheme":"file"}],{"providedKinds":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite"]},"rust-analyzer"]
[ERROR]    +2ms Oni2.Extension.ClientStore : Unhandled method: $registerFoldingRangeProvider - Args: [15,[{"$serialized":true,"language":"rust","scheme":"file"}]]
[ERROR]    +0ms Oni2.Extension.ClientStore : Unhandled method: $registerSelectionRangeProvider - Args: [16,[{"$serialized":true,"language":"rust","scheme":"file"}]]
[ERROR]    +0ms Oni2.Extension.ClientStore : Unhandled method: $registerCallHierarchyProvider - Args: [17,[{"$serialized":true,"language":"rust","scheme":"file"}]]
[ERROR]    +1ms Oni2.Extension.ClientStore : Unhandled method: $registerDocumentSemanticTokensProvider - Args: [18,[{"$serialized":true,"language":"rust","scheme":"file"}],{"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","consuming","unsafe","attribute"],"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","typeParameter","function","member","property","macro","variable","parameter","label","attribute","boolean","builtinType","enumMember","escapeSequence","formatSpecifier","generic","lifetime","punctuation","selfKeyword","typeAlias","union","unresolvedReference"]},null]
[ERROR]    +1ms Oni2.Extension.ClientStore : Unhandled method: $registerDocumentRangeSemanticTokensProvider - Args: [19,[{"$serialized":true,"language":"rust","scheme":"file"}],{"tokenModifiers":["documentation","declaration","definition","static","abstract","deprecated","readonly","constant","controlFlow","injected","mutable","consuming","unsafe","attribute"],"tokenTypes":["comment","keyword","string","number","regexp","operator","namespace","type","struct","class","interface","enum","typeParameter","function","member","property","macro","variable","parameter","label","attribute","boolean","builtinType","enumMember","escapeSequence","formatSpecifier","generic","lifetime","punctuation","selfKeyword","typeAlias","union","unresolvedReference"]}]
[ERROR]    +1ms Oni2.Extension.ClientStore : Unhandled method: $setLanguageConfiguration - Args: [22,"ra_syntax_tree",{"brackets":[["[",")"]]}]
[ERROR]  +602ms Oni2.Extension.ClientStore : I tried the following decoders but they all failed:
  "string" decoder: Expected a string, but got null 
  "int" decoder: Expected an int, but got null 
  "float" decoder: Expected a float, but got null  
[ERROR]    +9ms Oni2.Extension.ClientStore : I tried the following decoders but they all failed:
  "string" decoder: Expected a string, but got null 
  "int" decoder: Expected an int, but got null 
  "float" decoder: Expected a float, but got null  
[ERROR]   +91ms Oni2.Extension.ClientStore : Expected an int, but got 96.15384615384616
[ERROR] +1562ms Oni2.Extension.ClientStore : Unknown message - type: 6
[ERROR] +12.46s Oni2.Extension.ClientStore : Unable to parse OutputService method: $reveal
```

**Comment by bryphe** [comment]
Looks like there are a couple issues:

This: 
```
[ERROR]  +602ms Oni2.Extension.ClientStore : I tried the following decoders but they all failed:
  "string" decoder: Expected a string, but got null 
  "int" decoder: Expected an int, but got null 
  "float" decoder: Expected a float, but got null  
```

is due to our status bar $setEntry parsing - the `priority` field happens to be null, but we expect an integer.

After that is unblocked, I see this in the LSP logs:
```
WARN [9/2/2020, 2:08:17 PM]: LSP request failed {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///d%3A%5Chello-rust%5Csrc%5Cmain.rs' }
  },
  error: [ResponseError: url is not a file
  	at handleResponse (c:\Users\bryphe\AppData\Local\Oni2\extensions\matklad.rust-analyzer-0.2.297\out\src\main.js:3413:48)
  	at processMessageQueue (c:\Users\bryphe\AppData\Local\Oni2\extensions\matklad.rust-analyzer-0.2.297\out\src\main.js:3238:17)
  	at Immediate.<anonymous> (c:\Users\bryphe\AppData\Local\Oni2\extensions\matklad.rust-analyzer-0.2.297\out\src\main.js:3222:13)
  	at processImmediate (internal/timers.js:456:21)] {
    code: -32603,
    data: undefined
  }
}
```

Looks like there may be a bug with how we are sending the file URL

**Comment by bryphe** [comment]
...and this is what would be expected:
```
> URI.URI.file("D:/hello-rust/src/main.rs").toString()
'file:///d%3A/hello-rust/src/main.rs'
```

**Comment by bryphe** [comment]
Cool, looks like fixing that URL unblocks the `rust-analyzer` extension on Windows:
![image](https://user-images.githubusercontent.com/13532591/92048276-20a92c80-ed3c-11ea-9315-280d4e856b9f.png)
