### ISSUE TITLE
Windows 10: fatal error C1083: Cannot open include file: 'v8.h'

### ISSUE THREAD

**Issue by parkerault** [onivim/oni2#2470]
While attempting to build from source, the `node install-node-dependencies.js` step is failing.
```
-- Production: false
Installing packages at: C:\Users\user\Documents\projects\oni2\node
Running: C:\Users\user\Documents\projects\oni2\vendor\node-v12.17.0\win-x64\node.exe | ["C:\\Users\\user\\Documents\\projects\\oni2\\vendor\\yarn-v1.14.0\\yarn-1.14.0.js","install","--flat","--production=true"]
yarn install v1.14.0
warning ..\package.json: "dependencies" has dependency "ocaml" with range "~4.7.0" that collides with a dependency in "devDependencies" of the same name with version "~4.10"
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "graceful-fs@4.2.3". Ignoring it.
warning Lockfile has incorrect entry for "debug@3.1.0". Ignoring it.
warning Lockfile has incorrect entry for "agent-base@~4.2.1". Ignoring it.
warning Lockfile has incorrect entry for "ms@2.0.0". Ignoring it.
warning Lockfile has incorrect entry for "graceful-fs@^4.2.0". Ignoring it.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠠ native-watchdog
[2/3] ⠠ node-pty
error C:\Users\user\Documents\projects\oni2\node\node_modules\spdlog: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\user\Documents\projects\oni2\node\node_modules\spdlog
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.0
gyp info using node@12.17.0 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\user\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1259) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\user\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\Documents\\projects\\oni2\\node\\node_modules\\spdlog\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\12.17.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\AppData\\Local\\node-gyp\\Cache\\12.17.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.17.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\user\\Documents\\projects\\oni2\\node\\node_modules\\spdlog',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\user\\Documents\\projects\\oni2\\node\\node_modules\\spdlog\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  logger.cc
  win_delay_load_hook.cc
c:\users\user\appdata\local\node-gyp\cache\12.17.0\include\node\node.h(67): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory (compiling source file ..\src\logger.cc) [C:\Users\user\Documents\projects\oni2\node\node_modules\spdlog\build\spdlog.vcxproj]
c:\users\user\appdata\local\node-gyp\cache\12.17.0\include\node\node.h(67): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory (compiling source file ..\src\main.cc) [C:\Users\user\Documents\projects\oni2\node\node_modules\spdlog\build\spdlog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\user\\Documents\\projects\\oni2\\vendor\\node-v12.17.0\\win-x64\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Documents\projects\oni2\node\node_modules\spdlog
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v7.1.0
```
OS version:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎1/‎9/‎2020
OS build	19042.508
Experience	Windows Feature Experience Pack 120.2212.31.0
```

**Comment by aidam38** [comment]
Any progress on this?
