### ISSUE TITLE
Extension Host error reply crashes Oni

### ISSUE THREAD

**Issue by despairblue** [onivim/oni2#2752]
When I type `Record<string, string>` the TS 4.0.5 returns an error which then crashes Oni.

Tracing I get this:

```
[INFO]  [ 7.488s] Oni2.Store.dispatch : dispatch: (TextInput ("c", <opaque>))
[DEBUG] [ 7.489s] Oni2.Store.dispatch : After: (TextInput ("c", <opaque>))
[TRACE] [ 7.489s] Revery.Tick : Tick.pump - starting with 2 active tickers.
[TRACE] [ 7.489s] Revery.Tick : Interval - running timer: Oni2_Editor Apploop 0
[TRACE] [ 7.489s] Exthost.Transport : Read 9512 bytes
[TRACE] [ 7.489s] Exthost.Client : RequestJSONArgs: 594 10 $changeMany
[INFO]  [ 7.489s] Oni2.Store.dispatch : dispatch: (Diagnostics (Feature_Diagnostics.Set <opaque>))
[DEBUG] [ 7.492s] Oni2.Store.dispatch : After: (Diagnostics (Feature_Diagnostics.Set <opaque>))
[TRACE] [ 7.492s] Exthost.Client : Responding to request 594 with OkEmpty
[INFO]  [ 7.492s] Exthost.Client : Sending message: Exthost_Protocol.Message.Outgoing.ReplyOKEmpty {requestId = 594}
[TRACE] [ 7.492s] Exthost.Transport : Sending 18 bytes
[TRACE] [ 7.492s] Exthost.Client : RequestJSONArgs: 595 27 $dispose
[INFO]  [ 7.492s] Oni2.Store.dispatch : dispatch: (StatusBar (Feature_StatusBar.ItemDisposed "3"))
[DEBUG] [ 7.493s] Oni2.Store.dispatch : After: (StatusBar (Feature_StatusBar.ItemDisposed "3"))
[TRACE] [ 7.493s] Exthost.Client : Responding to request 595 with OkEmpty
[INFO]  [ 7.493s] Exthost.Client : Sending message: Exthost_Protocol.Message.Outgoing.ReplyOKEmpty {requestId = 595}
[TRACE] [ 7.493s] Exthost.Transport : Sending 18 bytes
[INFO]  [ 7.493s] Oni2.Store.dispatch : dispatch: (LanguageSupport
   (Feature_LanguageSupport.Completion
      (Completion.Provider
         (Completion.Exthost
            CompletionProvider.DetailsError {handle = 13;
              errorMsg =
              "Exthost__Client.ReplyError(\"{\\\"$isError\\\":true,\\\"name\\\":\\\"Error\\\",\\\"message\\\":\\\"<semantic> TypeScript Server Error (4.0.5)\\\\nDebug Failure. False expression: Some exportInfo should match the specified moduleSymbol\\\\nError: Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol\\\\n    at getImportFixForSymbol (tsserver.js:133042:22)\\\\n    at Object.getImportCompletionAction (tsserver.js:133037:23)\\\\n    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:115541:33)\\\\n    at Object.getCompletionEntryDetails (tsserver.js:115505:30)\\\\n    at Object.getCompletionEntryDetails (tsserver.js:143549:35)\\\\n    at tsserver.js:154413:57\\\\n    at Object.mapDefined (tsserver.js:610:30)\\\\n    at IOSession.Session.getCompletionEntryDetails (tsserver.js:154411:33)\\\\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (tsserver.js:153276:61)\\\\n    at tsserver.js:155017:88\\\\n    at IOSession.Session.executeWithRequestId (tsserver.js:155008:28)\\\\n    at IOSession.Session.executeCommand (tsserver.js:155017:33)\\\\n    at IOSession.Session.onMessage (tsserver.js:155041:35)\\\\n    at Interface.<anonymous> (tsserver.js:157257:27)\\\\n    at Interface.emit (events.js:315:20)\\\\n    at Interface._onLine (readline.js:329:10)\\\\n    at Interface._normalWrite (readline.js:474:12)\\\\n    at Socket.ondata (readline.js:186:10)\\\\n    at Socket.emit (events.js:315:20)\\\\n    at addChunk (_stream_readable.js:295:12)\\\\n    at readableAddChunk (_stream_readable.js:271:9)\\\\n    at Socket.Readable.push (_stream_readable.js:212:10)\\\\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)\\\",\\\"stack\\\":\\\"Error: <semantic> TypeScript Server Error (4.0.5)\\\\nDebug Failure. False expression: Some exportInfo should match the specified moduleSymbol\\\\nError: Debug Failure. False expression: Some exportInfo should match the specified moduleSymbol\\\\n    at getImportFixForSymbol (tsserver.js:133042:22)\\\\n    at Object.getImportCompletionAction (tsserver.js:133037:23)\\\\n    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:115541:33)\\\\n    at Object.getCompletionEntryDetails (tsserver.js:115505:30)\\\\n    at Object.getCompletionEntryDetails (tsserver.js:143549:35)\\\\n    at tsserver.js:154413:57\\\\n    at Object.mapDefined (tsserver.js:610:30)\\\\n    at IOSession.Session.getCompletionEntryDetails (tsserver.js:154411:33)\\\\n    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (tsserver.js:153276:61)\\\\n    at tsserver.js:155017:88\\\\n    at IOSession.Session.executeWithRequestId (tsserver.js:155008:28)\\\\n    at IOSession.Session.executeCommand (tsserver.js:155017:33)\\\\n    at IOSession.Session.onMessage (tsserver.js:155041:35)\\\\n    at Interface.<anonymous> (tsserver.js:157257:27)\\\\n    at Interface.emit (events.js:315:20)\\\\n    at Interface._onLine (readline.js:329:10)\\\\n    at Interface._normalWrite (readline.js:474:12)\\\\n    at Socket.ondata (readline.js:186:10)\\\\n    at Socket.emit (events.js:315:20)\\\\n    at addChunk (_stream_readable.js:295:12)\\\\n    at readableAddChunk (_stream_readable.js:271:9)\\\\n    at Socket.Readable.push (_stream_readable.js:212:10)\\\\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)\\\\n\\\\tat Function.create (/tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/tsServer/serverError.js:19:16)\\\\n\\\\tat ProcessBasedTsServer.dispatchResponse (/tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/tsServer/server.js:143:70)\\\\n\\\\tat ProcessBasedTsServer.dispatchMessage (/tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/tsServer/server.js:85:30)\\\\n\\\\tat /tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/tsServer/server.js:58:45\\\\n\\\\tat Emitter.fire (/tmp/.mount_oniK9xsiK/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:456:38)\\\\n\\\\tat Reader.onLengthData (/tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/utils/wireProtocol.js:112:30)\\\\n\\\\tat Socket.<anonymous> (/tmp/.mount_oniK9xsiK/usr/bin/extensions/typescript-language-features/out/utils/wireProtocol.js:91:42)\\\\n\\\\tat Socket.emit (events.js:315:20)\\\\n\\\\tat addChunk (_stream_readable.js:295:12)\\\\n\\\\tat readableAddChunk (_stream_readable.js:271:9)\\\\n\\\\tat Socket.Readable.push (_stream_readable.js:212:10)\\\\n\\\\tat Pipe.onStreamRead (internal/stream_base_commons.js:186:23)\\\"}\")"}))))
```

Here is a video showing it: https://youtu.be/qZibU_ga8yw (HD is still being processed)

I checked for core dumps, but none were created.

**Comment by bryphe** [comment]
Thanks for all the details @despairblue and taking the video - was very helpful! I can reproduce this and looking at a fix - we certainly shouldn't be crashing in this case.

**Comment by bryphe** [comment]
Putting together a fix for the crash in #2760 

I suspect the underlying error is due to our typescript extension being out-of-date

**Comment by bryphe** [comment]
Actually, it sounds like this callstack is an underlying bug with the typescript language services: https://github.com/microsoft/TypeScript/issues/38071

**Comment by despairblue** [comment]
Huh, interesting. Then should oni try to restart the TS server? Or just report it. Otherwise one may loose unsaved data.

**Comment by despairblue** [comment]
Ah, that's what you're fix does. Yeah, seems like the best way to go there. It does not look like somebody at microsoft/typescript is working to fix it. Probably also hard to reproduce for them.
