### ISSUE TITLE
App not launching - Ubuntu 16.04

### ISSUE THREAD

**Issue by DelError** [onivim/oni2#3124]
Hey there,

before starting with the issue I'm experiencing, let me tell you: I've just purchased the Alpha and I highly appreciate your project and the effort you put into it.
The idea of a full fledged IDE on the basis of VIM is so great. Let's face it: VIM (and NeoVIM) is a great, powerful tool, but setting up IDE-like features like code-completion, jump to definition etc. is just a pain, especially when working with multiple programming languages.

Now, for the actual bug report.
I tried running the latest nightly build (Onivim 2 0.5.9-nightly) on a freshly installed Ubuntu 16.04 (I'm actually using ZorinOS on basis of Ubuntu 16.04 but I wanted to make sure that the problem also occurs on a clean and unchanged Ubuntu 16.04).

When starting the AppImage, a new black window pops up for a second or so and closes immediately.
I tried running the AppImage with `-f --debug` and found the following error at the very end of the log:

```
[DEBUG] [  0.404s] Oni2.Store.StoreThread : Effect complete: Batch:
vim.init
Batch:
  exthost.registerQuitCleanup
  exthost.discoverExtensions

configuration.init
keyBindings.load

/tmp.mount_OnivimowSGs4/usr/bin/Oni2_editor: symbol lookup error: /tmp/.mount_OnivimowSGs4/usr/lib/libgtk-3.so.0: undefined symbol: g_log_structured_standard

Error: connect ECONNREFUSED /tmp/exthost-0b6820-sock1
   at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '/tmp/exthost-0b6820-sock1'
}
```

I found a similar issue for Linux Mint 18.1 here: #2459 

`cat /etc/os-release`:
```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

And `ldd --version`:
```
ldd (Ubuntu GLIBC 2.23-0ubuntu11.2) 2.23
```

For me personally this is not a huge problem as I am about to migrate to Ubuntu 20 anyways, so I just need a few more week of patience until I can use Onivim 2 and Ubuntu support ends at end of April this year.
It's just stated as "tested on" system here: https://onivim.github.io/docs/getting-started/installation
Therefore I thought in order to have a complete overview it would be alright to report this issue.

**Comment by bryphe** [comment]
Thanks for all the details, @DelError (and the kind words! 😄 ) ! Indeed looks similar to #2549 

I suspect there is a `GLIBC` mismatch. We build on CentOS 7, with glibc `2.17`, and Ubuntu 16 uses glibc `2.23`, so we should be OK. We actually test running the health check on [Ubuntu 16 in our CI](https://github.com/onivim/oni2/blob/07ac590aebe6d7834cdb2720604c873ae685773c/azure-pipelines.yml#L215):
![image](https://user-images.githubusercontent.com/13532591/107722612-282e1380-6c94-11eb-8f2b-646ec6912b44.png)

to try and catch this sort of issue... but seems like we're missing something here.

I was searching around saw a mention of a similar error here: https://github.com/AppImage/pkg2appimage/blob/d61672ff4f90cf793a0bee7b056186fcdeb9b510/excludelist#L171 (although a different library is impacted).

It's interesting too that, based on the snippet in the log, it's gotten to the point of loading keybindings / configuration... would it be possible to see a log file constructed via `./Onivim2-x86_64.AppImage -f --log-file=startup.log`? Curious if there are any clues earlier.

I'll also set up a Ubuntu 16.04 machine and see if I can reproduce as well - it's possible our CI environment isn't sufficiently exercising this case.

> For me personally this is not a huge problem as I am about to migrate to Ubuntu 20 anyways, so I just need a few more week of patience until I can use Onivim 2 and Ubuntu support ends at end of April this year.

Phew, glad it's not a complete blocker 😄

**Comment by DelError** [comment]
Thanks @bryphe for your response.
Here is the log file you asked for:
[startup.log](https://github.com/onivim/oni2/files/5969751/startup.log)

Side note: the part at the end:
```
/tmp/.mount_OnivimDcNrCG/usr/bin/Oni2_editor: symbol lookup error: /tmp/.mount_OnivimDcNrCG/usr/lib/libgtk-3.so.0: undefined symbol: g_log_structured_standard
delerror@delerror-machine:~/Downloads$ Error: connect ECONNREFUSED /tmp/exthost-57cbde-sock1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/exthost-57cbde-sock1'
}
```
was copied into the log file manually as it was not appended automatically by `--log-file`

I honestly had not expected that you would still look into this issue as Ubuntu support ends so soon (just about 3 months to go), but it's still great to see 😄 



> I was searching around saw a mention of a similar error here: https://github.com/AppImage/pkg2appimage/blob/d61672ff4f90cf793a0bee7b056186fcdeb9b510/excludelist#L171 (although a different library is impacted).

Yes, when googling the issue (since I suspected my Ubuntu16.04 installation being the problem) I found several problems like this, caused by several different libraries. Seems to be a common thing.

Kind regards.
