### ISSUE TITLE
Crash when removing lines in TypeScript

### ISSUE THREAD

**Issue by marcinkoziej** [onivim/oni2#3323]
# What happened?

1. Openend a TypeScript file
2. Marked unused imports with `V`
3. Pressed `d`
4. Crash!

![oni-crash](https://user-images.githubusercontent.com/156725/112217400-e2fde980-8c22-11eb-951f-5bdb62d69403.gif)

# Logs
```
[INFO]  [18.206s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: d
 WithShift: D
 WithAltGr: ð
 WithAltGrShift: Ð


[INFO]  [18.206s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: d
 WithShift: D
 WithAltGr: ð
 WithAltGrShift: Ð


[INFO]  [18.206s] Oni2.Store.dispatch : dispatch: KeyDown {
  key =
  [(KeyPress.PhysicalKey
      { PhysicalKey.key = (Key.Character <opaque>);
        modifiers =
        { Modifiers.control = false; alt = false; altGr = false;
          shift = false; super = false }
        })
    ];
  scancode = 7; time = <opaque>}
[DEBUG] [18.207s] Oni2.Store.dispatch : After: KeyDown {
  key =
  [(KeyPress.PhysicalKey
      { PhysicalKey.key = (Key.Character <opaque>);
        modifiers =
        { Modifiers.control = false; alt = false; altGr = false;
          shift = false; super = false }
        })
    ];
  scancode = 7; time = <opaque>}
[INFO]  [18.207s] Oni2.Store.dispatch : dispatch: (TextInput ("d", <opaque>))
[DEBUG] [18.207s] Oni2.Store.dispatch : After: (TextInput ("d", <opaque>))
[DEBUG] [18.207s] Oni2.Store.StoreThread : Running effect: Batch:
 input.immediateDispatch

[DEBUG] [18.207s] Oni2.Store.StoreThread : Effect complete: Batch:
 input.immediateDispatch

[DEBUG] [18.207s] Oni2.Store.StoreThread : Running effect: Batch:
 input.immediateDispatch

[INFO]  [18.207s] Oni2.Store.dispatch : dispatch: KeyboardInput {isText = true; input = "d"}
[DEBUG] [18.208s] Oni2.Store.dispatch : After: KeyboardInput {isText = true; input = "d"}
[INFO]  [18.208s] Oni2.Store.dispatch : dispatch: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "d")))
[DEBUG] [18.208s] Oni2.Store.dispatch : After: (LanguageSupport (Feature_LanguageSupport.Hover (KeyPressed "d")))
[DEBUG] [18.208s] Oni2.Store.StoreThread : Running effect: Batch:
 vim.input

[DEBUG] [18.208s] Oni2.Store.Vim : Buffer update: 3
[INFO]  [18.208s] Oni2.Store.dispatch : dispatch: (Buffers
   Update {update = <opaque>; oldBuffer = <opaque>; newBuffer = <opaque>;
     triggerKey = (Some "d")})
[DEBUG] [18.209s] Oni2.Store.dispatch : After: (Buffers
   Update {update = <opaque>; oldBuffer = <opaque>; newBuffer = <opaque>;
     triggerKey = (Some "d")})
[DEBUG] [18.209s] Oni2.Store.Vim : Buffer metadata changed: 3 | true
[INFO]  [18.209s] Oni2.Store.dispatch : dispatch: (Buffers (ModifiedSet (3, true)))
[DEBUG] [18.209s] Oni2.Store.dispatch : After: (Buffers (ModifiedSet (3, true)))
[INFO]  [18.210s] Oni2.Store.dispatch : dispatch: (Vim
   Feature_Vim.ModeChanged {allowAnimation = true; mode = <opaque>;
     subMode = <opaque>; effects = <opaque>})
[DEBUG] [18.211s] Oni2.Store.dispatch : After: (Vim
   Feature_Vim.ModeChanged {allowAnimation = true; mode = <opaque>;
     subMode = <opaque>; effects = <opaque>})
[DEBUG] [18.211s] Oni2.Store.Vim : handled key: d
[DEBUG] [18.211s] Oni2.Store.StoreThread : Effect complete: Batch:
 vim.input

[DEBUG] [18.211s] Oni2.Store.StoreThread : Effect complete: Batch:
 input.immediateDispatch

[INFO]  [18.211s] Oni2_editor : Setting title: *forms.tsx - proca-admin - Onivim 2
[DEBUG] [18.212s] Revery.App : Upshifting into active state.
[ERROR] [18.213s] Oni2.Exception : Exception (Invalid_argument "index out of bounds"):
Raised by primitive operation at file "src/Core/Buffer.re", line 188, characters 40-65
Called from file "src/Feature/Diagnostics/Diagnostic.re", line 28, characters 8-83
Called from file "src/editor-core-types/CharacterRange.re", line 20, characters 23-34
Called from file "src/Feature/Diagnostics/Diagnostic.re", line 35, characters 2-51
Called from file "list.ml", line 103, characters 22-25
Called from file "src/Core/Utility/ListEx.re" (inlined), line 3, characters 27-62
Called from file "src/Feature/Diagnostics/Feature_Diagnostics.re", line 119, characters 4-59
Called from file "src/Feature/Diagnostics/Feature_Diagnostics.re" (inlined), line 272, characters 46-124
Called from file "src/Feature/Editor/EditorSurface.re", line 236, characters 4-62
Called from file "lib/Brisk_reconciler_internal.re", line 827, characters 12-205
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1299, characters 16-453
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 1419, characters 12-443
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1185, characters 12-180
Called from file "lib/Brisk_reconciler_internal.re", line 858, characters 12-236
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 1419, characters 12-443
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1342, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1086, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1063, characters 10-1023
Called from file "lib/Brisk_reconciler_internal.re", line 911, characters 14-785
Called from file "lib/Brisk_reconciler_internal.re", line 731, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1185, characters 12-180
Called from file "src/UI/Container.re", line 32, characters 10-161
Called from file "src/UI/Render.re", line 27, characters 17-56
Called from file "src/UI/Render.re", line 26, characters 2-99
Called from file "src/UI/Ui.re", line 187, characters 26-76
Called from file "src/Core/Window.re", line 399, characters 2-17
Called from file "list.ml", line 110, characters 12-15
Called from file "src/Core/App.re", line 298, characters 6-123
Called from file "packages/reason-sdl2/src/sdl2.re", line 898, characters 10-20
Called from file "packages/reason-sdl2/src/sdl2.re", line 344, characters 17-59
Called from file "packages/reason-sdl2/src/sdl2.re", line 344, characters 17-59
Called from file "src/bin_editor/Oni2_editor.re", line 535, characters 11-26

marcin $ <<<<< XXX got shell here

 Unhandled Promise Rejection:  [Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at writeAfterEnd (_stream_writable.js:266:14)
	at Socket.Writable.write (_stream_writable.js:315:5)
	at /home/marcin/.config/oni2/extensions/golang.Go-0.22.0/dist/goMain.js:76103:29
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (/home/marcin/.config/oni2/extensions/golang.Go-0.22.0/dist/goMain.js:76093:16)
	at StreamMessageWriter.doWrite (/home/marcin/.config/oni2/extensions/golang.Go-0.22.0/dist/goMain.js:76641:33)
	at /home/marcin/.config/oni2/extensions/golang.Go-0.22.0/dist/goMain.js:76632:29] {
  code: 'ERR_STREAM_WRITE_AFTER_END'
```

# Platform
Ubuntu 20.04
Oni2 built from master on 17-03-2021

**Comment by bryphe** [comment]
Hey @marcinkoziej , sorry you hit this! Thanks for including the log entry - it's really helpful.

This should be fixed by https://github.com/onivim/oni2/pull/3297 - so grabbing the latest `master` should address it.

There was a bug due to our processing of minimal updates and shifting diagnostics - essentially, in the case shown above, we'd shift the diagnostics immediately - but a boundary case was missed, and they'd get shifted to a negative line number, which causes all sorts of problems, including that crash.

I realized looking at https://github.com/onivim/oni2/pull/3297 that we're missing an integration test for this, so I'll use this issue to track adding integration test coverage so we can avoid a bug like this in future :+1:

**Comment by marcinkoziej** [comment]
@bryphe You are awesome!
