### ISSUE TITLE
Python Extension runtime error ms-python: Unknown FileSystemError: Utility__LuvEx.LuvException(877502405)

### ISSUE THREAD

**Issue by JoseConseco** [onivim/oni2#3418]
When I open python file I always get this error (status line flashes red but everything seems to be working fine in the end):
```
Unhandled Promise Rejection:  [Unknown (FileSystemError): Utility__LuvEx.LuvException(877502405)
	at _handleError (/tmp/.mount_Onivimbt7svk/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostFileSystemConsumer.js:57:23)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async g.createDirectory (/home/bartosz/.config/oni2/extensions/ms-python.python-2020.10.332292344.vsix/out/client/extension.js:56:216765)
	at async g.createLocalDirectory (/home/bartosz/.config/oni2/extensions/ms-python.python-2020.10.332292344.vsix/out/client/extension.js:56:215216)
	at async p.initDir (/home/bartosz/.config/oni2/extensions/ms-python.python-2020.10.332292344.vsix/out/client/extension.js:56:326619)] {
  code: 'Unknown'
}

```
![obraz](https://user-images.githubusercontent.com/13521338/114864378-38c44c80-9df1-11eb-91fc-53ef31f452c1.png)
Full log (copied from console since --log-file - cuts the  'interesting' part) :
[oni_python_ext.log](https://github.com/onivim/oni2/files/6317712/oni_python_ext.log)

I'm on manjaro, using daily AppImage build  form 15th of april. 
BTW. also  Ctrl+P - does not work in normal mode (work in visual though).

**Comment by bryphe** [comment]
Thanks for logging the issue and for grabbing the error and the log, @JoseConseco !

I can reproduce on Manjaro as well - it seems like there are a couple issues:
1) When there is a file system error, we aren't sending it to the extension host in the format it expects (the python extension, in particular, expects them to be in a specific format to match on the proper error)
2) There are a couple cases where the python extension is writing to configuration directories, that it expects the directories to be created (which we aren't handling, at the moment).

**Comment by Govinda-Fichtner** [comment]
It seems I do have the same error on Mac OS X 10.15.7 with Oni2 v0.5.9-nightly and Python 3.9.2:

```
oni2 --query-extension ms-python.python
Extension Python:
- Description: Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more.
- Homepage: https://github.com/open-vsx
- Download Url: https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix
- Versions:
 - Version 2020.10.332292344: https://open-vsx.org/api/ms-python/python/2020.10.332292344
 - Version 2020.9.112786: https://open-vsx.org/api/ms-python/python/2020.9.112786
 - Version 2020.9.111407: https://open-vsx.org/api/ms-python/python/2020.9.111407
 - Version 2020.8.105369: https://open-vsx.org/api/ms-python/python/2020.8.105369
 - Version 2020.8.105045: https://open-vsx.org/api/ms-python/python/2020.8.105045
 - Version 2020.8.101144: https://open-vsx.org/api/ms-python/python/2020.8.101144
 - Version 2020.7.96456: https://open-vsx.org/api/ms-python/python/2020.7.96456
 - Version 2020.7.1: https://open-vsx.org/api/ms-python/python/2020.7.1
 - Version 2020.7.0: https://open-vsx.org/api/ms-python/python/2020.7.0
 - Version 2020.6.1: https://open-vsx.org/api/ms-python/python/2020.6.1
 - Version 2019.11.1: https://open-vsx.org/api/ms-python/python/2019.11.1
 ```
