### ISSUE TITLE
[Extension] Rewrap extension not working

### ISSUE THREAD

**Issue by jesstelford** [onivim/oni2#3545]
I've installed [Rewrap](https://github.com/stkb/Rewrap) `v1.14.0` in Onivim 2 `v0.5.9-nightly (0.5.2102)` on MacOS.

I've setup a keybinding:

```json
  {
    "key": "gq",
    "command": "rewrap.rewrapComment",
    "when": "editorTextFocus && !insertMode"
  }
```

Then when I move my cursor into the following file, and hit `gq`, I get the below error:

`tmp.tsx`
```javascript
/**
 * DO a thin
 * g that is awesome and we love it this is a long. Sentence that should wrap I
 * hope, we'll have to see?
 *
 * What about line breaks?
 *
 * 1. Number 1
 * 2. two
 * 3. three
 */
```

The relevant error output is:

```
====== Rewrap: Error ======                                                                                                                          [376/93547]
[TypeError: Cannot read property 'isEqual' of undefined
        at Object.applyEdit (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Common.js:22:44)
        at doWrap (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Extension.js:59:25)
        at rewrapCommentCommand (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Extension.js:16:9)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHost.api.impl.js:159:38
        at Object.edit (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostTextEditor.js:3
46:21)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHost.api.impl.js:158:49
        at ExtHostCommands._executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/ap
i/common/extHostCommands.js:164:39)
        at ExtHostCommands.$executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/ap
i/common/extHostCommands.js:186:29)
        at RPCProtocol._doInvokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensi
ons/common/rpcProtocol.js:348:27)
        at RPCProtocol._invokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extension
s/common/rpcProtocol.js:333:45)
        at RPCProtocol._receiveRequest (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensio
ns/common/rpcProtocol.js:260:32)
        at RPCProtocol._receiveOneMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/exten
sions/common/rpcProtocol.js:188:26)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:5
2
        at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
        at BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:3
75:35)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/node/extensionHostProcessS
etup.js:146:41
        at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
        at BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:3
75:35)
        at PersistentProtocol._receiveMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/commo
n/ipc.net.js:654:41)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:510:83
        at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
        at ProtocolReader.acceptChunk (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.ne
t.js:189:37)
        at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:158:61
        at Socket.listener (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)]
^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
```

<details>
  <summary>Click to see the full output from Onivim:</summary>

  ```
  [INFO]  [232.701s] Oni2.Store.dispatch : dispatch: WindowFocusGained
  [INFO]  [234.090s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: g
   WithShift: G
   WithAltGr: ©
   WithAltGrShift: ˝
  
  
  [INFO]  [234.090s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: g
   WithShift: G
   WithAltGr: ©
   WithAltGrShift: ˝
  
  
  [INFO]  [234.090s] Oni2.Store.dispatch : dispatch: KeyDown {
    key =
    [(KeyPress.PhysicalKey
        { PhysicalKey.key = (Key.Character <opaque>);
          modifiers =
          { Modifiers.control = false; alt = false; altGr = false;
            shift = false; super = false }
          })
      ];
    scancode = 10; time = <opaque>}
  [INFO]  [234.093s] Oni2.Store.dispatch : dispatch: (TextInput ("g", <opaque>))
  [INFO]  [234.156s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: q
   WithShift: Q
   WithAltGr: œ
   WithAltGrShift: Œ
  
  
  [INFO]  [234.156s] Feature.Input.ReveryKeyConverter : Key info: Unmodified: q
   WithShift: Q
   WithAltGr: œ
   WithAltGrShift: Œ
  
  
  [INFO]  [234.157s] Oni2.Store.dispatch : dispatch: KeyDown {
    key =
    [(KeyPress.PhysicalKey
        { PhysicalKey.key = (Key.Character <opaque>);
          modifiers =
          { Modifiers.control = false; alt = false; altGr = false;
            shift = false; super = false }
          })
      ];
    scancode = 20; time = <opaque>}
  [INFO]  [234.159s] Oni2.Store.dispatch : dispatch: (TextInput ("q", <opaque>))
  [INFO]  [234.163s] Oni2.Store.dispatch : dispatch: KeybindingInvoked {command = "rewrap.rewrapComment"; arguments = `Null}
  [INFO]  [234.166s] Oni2.Store.dispatch : dispatch: (Extensions
     ExecuteCommand {command = "rewrap.rewrapComment"; arguments = <opaque>})
  ====== Rewrap: Error ======
  [TypeError: Cannot read property 'isEqual' of undefined
          at Object.applyEdit (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Common.js:22:44)
          at doWrap (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Extension.js:59:25)
          at rewrapCommentCommand (/Users/jess/.config/oni2/extensions/stkb.rewrap-1.14.0/vscode/compiled/Extension.js:16:9)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHost.api.impl.js:159:38
          at Object.edit (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostTextEditor.js:346:21)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHost.api.impl.js:158:49
          at ExtHostCommands._executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostCommands.js:164:39)
          at ExtHostCommands.$executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostCommands.js:186:29)
          at RPCProtocol._doInvokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)
          at RPCProtocol._invokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)
          at RPCProtocol._receiveRequest (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)
          at RPCProtocol._receiveOneMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52
          at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
          at BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41
          at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
          at BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:375:35)
          at PersistentProtocol._receiveMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:654:41)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:510:83
          at Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)
          at ProtocolReader.acceptChunk (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:189:37)
          at /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:158:61
          at Socket.listener (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/node/ipc.net.js:33:40)
          at Socket.emit (events.js:315:20)
          at addChunk (internal/streams/readable.js:309:12)
          at readableAddChunk (internal/streams/readable.js:284:9)
          at Socket.Readable.push (internal/streams/readable.js:223:10)
          at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)]
  ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
  at https://github.com/stkb/vscode-rewrap/issues
  [INFO]  [234.193s] Oni2.Store.dispatch : dispatch: (Messages
     Feature_Messages.NotificationReceived {severity = Message.Info;
       message =
       "Sorry, there was an error in Rewrap. Go to: Help -> Toggle Developer Tools -> Console for more information."})
  [INFO]  [234.195s] Exthost.Client : Sending message: Exthost_Protocol.Message.Outgoing.ReplyOKEmpty {requestId = 386}
  [ERROR] [234.195s] Oni2.Extension.ClientStore : {"$isError":true,"name":"Error","message":"Running the contributed command: 'rewrap.rewrapComment' failed.","stack":"Error: Running the contributed command: 'rewrap.rewrapComment' failed.\n\tat ExtHostCommands._executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostCommands.js:176:23)\n\tat ExtHostCommands.$executeContributedCommand (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostCommands.js:186:29)\n\tat RPCProtocol._doInvokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:348:27)\n\tat RPCProtocol._invokeHandler (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:333:45)\n\tat RPCProtocol._receiveRequest (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:260:32)\n\tat RPCProtocol._receiveOneMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:188:26)\n\tat /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:69:52\n\tat Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)\n\tat BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:375:35)\n\tat /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:146:41\n\tat Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)\n\tat BufferedEmitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:375:35)\n\tat PersistentProtocol._receiveMessage (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:654:41)\n\tat /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:510:83\n\tat Emitter.fire (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/event.js:479:38)\n\tat ProtocolReader.acceptChunk (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:189:37)\n\tat /Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/common/ipc.net.js:158:61\n\tat Socket.listener (/Applications/Onivim2.app/Contents/Resources/node/node_modules/@onivim/vscode-exthost/out/vs/base/parts/ipc/node/ipc.net.js:33:40)\n\tat Socket.emit (events.js:315:20)\n\tat addChunk (internal/streams/readable.js:309:12)\n\tat readableAddChunk (internal/streams/readable.js:284:9)\n\tat Socket.Readable.push (internal/streams/readable.js:223:10)\n\tat Pipe.onStreamRead (internal/stream_base_commons.js:188:23)"}
  [INFO]  [234.196s] Oni2.Store.dispatch : dispatch: (Notification
     (Created
        { id = 3; kind = Info;
          message =
          "Sorry, there was an error in Rewrap. Go to: Help -> Toggle Developer Tools -> Console for more information.";
          source = None; ephemeral = false; yOffsetAnimation = <opaque> }))
  ```

</details>

**Comment by jesstelford** [comment]
I've also reported this on the Rewrap repo as I'm not sure if it's a bug in their code or not? (My hunch is it's a missing API in Onivim's LSP implementation?): https://github.com/stkb/Rewrap/issues/273

**Comment by bryphe** [comment]
Thanks for the repro and fetching the logs, @jesstelford !

There's two bugs on the Onivim side blocking this:
1) The extension is using `editor.selections` here https://github.com/stkb/Rewrap/blob/2c3bd14fd630679cbbb4127ed0d4e660a0bf077a/vscode/src/Extension.ts#L65 - this isn't populated correctly by Onivim, an d is the cause of the crash
2) Onivim isn't implementing the `$tryApplyEdits` API which is used by Rewrap to apply the edits, once it has a valid selection

**Comment by jesstelford** [comment]
Thanks for fixing this one @bryphe! I'll check it out in the next nightly and confirm it's working as expected 👍

**Comment by bryphe** [comment]
Awesome, thanks @jesstelford ! Feel free to re-open if you still have issues :+1:
