### ISSUE TITLE
Crash on workbench zoomIn

### ISSUE THREAD

**Issue by lobre** [onivim/oni2#3779]
I am running Oni2 on NixOS and using the latest AppImage from the `master` branch, the application is crashing when trying to activate `workbench.action.zoomIn` using the default shortcut.

Here is an extract of the log taken from the output of `oni2 -f`.

```
[INFO]  [ 4.481s] Oni2.Store.dispatch : dispatch: KeybindingInvoked {command = "workbench.action.zoomIn"; arguments = `Null}
[INFO]  [ 4.483s] Oni2.Store.dispatch : dispatch: (Zoom (Feature_Zoom.Command Feature_Zoom.ZoomIn))
Unhandled Promise Rejection:  [Canceled: Canceled
	at Object.canceled (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/errors.js:109:23)
	at RPCProtocol._remoteCall (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:352:46)
	at Proxy.target.<computed> (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/rpcProtocol.js:150:41)
	at _.<anonymous> (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostLanguageFeatures.js:1251:29)
	at _.dispose (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostTypes.js:56:78)
	at Object.dispose (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/base/common/lifecycle.js:77:27)
	at ExtHostExtensionService._deactivate (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostExtensionService.js:183:29)
	at /tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostExtensionService.js:102:33
	at Array.map (<anonymous>)
	at ExtHostExtensionService.deactivateAll (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/api/common/extHostExtensionService.js:101:51)
	at ExtensionHostMain.terminate (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/common/extensionHostMain.js:82:66)
	at onTerminate (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:279:53)
	at Socket.<anonymous> (/tmp/.mount_oni2UM4IZG/usr/share/node/node_modules/@onivim/vscode-exthost/out/vs/workbench/services/extensions/node/extensionHostProcessSetup.js:131:21)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)]
```

Thanks for your help

**Comment by bryphe** [comment]
Hi @lobre ,

Thanks for logging the issue - sorry you hit this!

I'm having trouble reproducing, but there's a few diagnostics that might help:
1) Does zooming out also cause a crash? (<kbd>Control</kbd>+<kdb>-</kdb>)
2) Does changing the `ui.zoom` property, instead of using the zoomIn/zoomOut binding, cause a crash?
3) Was there an `onivim2-crash.log` file left in the directory you ran Onivim 2 from? Might give us some clues
4) What keyboard layout are you using?

**Comment by lobre** [comment]
Hi @bryphe,

Thanks for the steps to help with the troubleshooting. I have understood the problem now.

My configuration file (`~/.config/oni2/configuration.json`) is managed using Nix (especially using [home manager](https://github.com/nix-community/home-manager)). This generates the configuration file as a read-only file that is symlinked to `~/.config/oni2/configuration.json`.

Here is my Nix configuration file (for reference): https://github.com/lobre/nix-home/blob/4e34ff5c1070d44b10f63cef3ae264dafedf3003/roles/hm/xfce/oni.nix

But apparently, Oni tries to write to this configuration file (in the `ui.zoom` setting) when the zoom is changed using a shortcut. But as my configuration file is read-only, it makes Oni crash.

So I am not sure there is a proper solution to my problem. I was just expecting that the current zoom was "dynamic", and not directly bound to the `ui.zoom` setting.

I am closing this issue as there isn’t much to do here.
Thanks again.
