### ISSUE TITLE
hi, windows build from source fails.

### ISSUE THREAD

**Issue by LollipopFt** [onivim/oni2#3837]
hi, i was trying to compile on windows when i ran into this error:
```
warning Lockfile has incorrect entry for "debug@4". Ignoring it.
warning Lockfile has incorrect entry for "debug@^4.3.1". Ignoring it.
warning Lockfile has incorrect entry for "http-proxy-agent@^2.1.0". Ignoring it.
warning Lockfile has incorrect entry for "https-proxy-agent@^2.2.4". Ignoring it.
warning Lockfile has incorrect entry for "agent-base@4". Ignoring it.
warning Lockfile has incorrect entry for "debug@3.1.0". Ignoring it.
warning Lockfile has incorrect entry for "ms@2.0.0". Ignoring it.
warning Lockfile has incorrect entry for "agent-base@^4.3.0". Ignoring it.
warning Lockfile has incorrect entry for "graceful-fs@4.2.6". Ignoring it.
warning Lockfile has incorrect entry for "node-pty@0.11.0-beta7". Ignoring it.
warning Lockfile has incorrect entry for "file-uri-to-path@1.0.0". Ignoring it.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⡀ native-watchdog
[2/4] ⡀ node-pty
[3/4] ⡀ spdlog
error C:\Users\lollipopft\oni2\node\node_modules\node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: C:\Users\lollipopft\oni2\node\node_modules\node-pty
Output:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node-gyp.cmd',
  path: 'node-gyp.cmd',



Process exited with code 1
stderr: null

C:\Users\lollipopft\oni2\install-node-deps.js:37
        throw result.error
        ^
undefined
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v17.0.1
```

system: ```Windows 10 Pro```
version: ```21H1```
node-gyp: ```node-gyp@8.4.0```
node: ```17.0.1```
npm: ```8.1.0```

**Comment by facepunch01** [comment]
what part of the compilation process caused this to happen
